---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "arbitrator-config"
  namespace: "default"
  labels:
    app: "arbitrator-app"
data:
  PROBLEM_FILE: "busy_day.in"
  ALLOC_FILE: "busy_day.alloc"
  GA_FORBIDDEN_STRATEGIES: "100" # 100 doesn't exist, won't filter out anything.
  GA_STRATEGIES_PER_DRONE: "1000"
  GA_STRATEGY_REPEATS: "3"
  GA_NUM_GENERATIONS: "200"
  GA_POPULATION_SIZE: "200"
  GA_SELECTION_SIZE: "80"
  GA_CROSSINGOVER_SIZE: "60"
  GA_MUTATION_SIZE: "60"
  GA_MUTATION_PROB: "0.05"
  GA_MAX_TWISTS: "5"
  GA_MUTATE_ALL_DRONES: "false"
---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "arbitrator-dep"
  namespace: "default"
  labels:
    app: "arbitrator-app"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "arbitrator-app"
  template:
    metadata:
      labels:
        app: "arbitrator-app"
    spec:
      containers:
      - name: "ga-arbitrator-image"
        image: "gcr.io/vs-gcp-drones/ga_arbitrator-image:latest"
        resources:
          requests: 
            memory: "2500Mi"
            cpu: "2000m"
        env:
        - name: "PROBLEM_FILE"
          valueFrom:
            configMapKeyRef:
              key: "PROBLEM_FILE"
              name: "arbitrator-config"
        - name: "ALLOC_FILE"
          valueFrom:
            configMapKeyRef:
              key: "ALLOC_FILE"
              name: "arbitrator-config"
        - name: "GA_FORBIDDEN_STRATEGIES"
          valueFrom:
            configMapKeyRef:
              key: "GA_FORBIDDEN_STRATEGIES"
              name: "arbitrator-config"
        - name: "GA_STRATEGIES_PER_DRONE"
          valueFrom:
            configMapKeyRef:
              key: "GA_STRATEGIES_PER_DRONE"
              name: "arbitrator-config"
        - name: "GA_STRATEGY_REPEATS"
          valueFrom:
            configMapKeyRef:
              key: "GA_STRATEGY_REPEATS"
              name: "arbitrator-config"
        - name: "GA_NUM_GENERATIONS"
          valueFrom:
            configMapKeyRef:
              key: "GA_NUM_GENERATIONS"
              name: "arbitrator-config"
        - name: "GA_POPULATION_SIZE"
          valueFrom:
            configMapKeyRef:
              key: "GA_POPULATION_SIZE"
              name: "arbitrator-config"
        - name: "GA_SELECTION_SIZE"
          valueFrom:
            configMapKeyRef:
              key: "GA_SELECTION_SIZE"
              name: "arbitrator-config"
        - name: "GA_CROSSINGOVER_SIZE"
          valueFrom:
            configMapKeyRef:
              key: "GA_CROSSINGOVER_SIZE"
              name: "arbitrator-config"
        - name: "GA_MUTATION_SIZE"
          valueFrom:
            configMapKeyRef:
              key: "GA_MUTATION_SIZE"
              name: "arbitrator-config"
        - name: "GA_MUTATION_PROB"
          valueFrom:
            configMapKeyRef:
              key: "GA_MUTATION_PROB"
              name: "arbitrator-config"
        - name: "GA_MAX_TWISTS"
          valueFrom:
            configMapKeyRef:
              key: "GA_MAX_TWISTS"
              name: "arbitrator-config"
        - name: "GA_MUTATE_ALL_DRONES"
          valueFrom:
            configMapKeyRef:
              key: "GA_MUTATE_ALL_DRONES"
              name: "arbitrator-config"

