---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "evaluator-config"
  namespace: "default"
  labels:
    app: "evaluator-app"
data:
  PROBLEM_FILE: "busy_day.in"
  ALLOC_FILE: "busy_day.alloc"
---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "evaluator-dep"
  namespace: "default"
  labels:
    app: "evaluator-app"
spec:
  replicas: 22
  selector:
    matchLabels:
      app: "evaluator-app"
  template:
    metadata:
      labels:
        app: "evaluator-app"
    spec:
      containers:
      - name: "ga-evaluator-image"
        image: "gcr.io/vs-gcp-drones/ga_evaluator-image:latest"
        ports:
        - containerPort: 12345
        env:
        - name: "PROBLEM_FILE"
          valueFrom:
            configMapKeyRef:
              key: "PROBLEM_FILE"
              name: "evaluator-config"
        - name: "ALLOC_FILE"
          valueFrom:
            configMapKeyRef:
              key: "ALLOC_FILE"
              name: "evaluator-config"
        resources:
          requests: 
            memory: "1500Mi"
            cpu: "3500m"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "evaluator-hpa"
  namespace: "default"
  labels:
    app: "evaluator-app"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "evaluator-dep"
    apiVersion: "apps/v1beta1"
  minReplicas: 22
  maxReplicas: 22 
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
---
apiVersion: v1
kind: Service
metadata:
  name: "evaluator"
spec:
  type: ClusterIP
  selector:
    app: "evaluator-app"
  ports:
  - name: "grpc-evaluator"
    #    protocol: TCP
    port: 12345
    targetPort: 12345

